version: '3'

services:
  
  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  postgres-melinforma:
    image: postgres
    container_name: postgres-melinforma
    restart: always
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: testuser
      POSTGRES_DB: COLABORA
      PGDATA: /data/postgres
    ports:
      - "8080:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "viniciussousavilela@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres-melinforma

networks:
  default:
    driver: bridge